// Date: 06.01.2018 01:47:31
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.zeldadungeons.client.render.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPonekins extends ModelBase
{
  //fields
    ModelRenderer leftLeg1;
    ModelRenderer leftLeg2;
    ModelRenderer rightLeg2;
    ModelRenderer rightLeg1;
    ModelRenderer b;
    ModelRenderer b1;
    ModelRenderer b2;
    ModelRenderer b3;
    ModelRenderer b4;
    ModelRenderer b5;
    ModelRenderer b6;
    ModelRenderer b7;
  
  public ModelPonekins()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      leftLeg1 = new ModelRenderer(this, 40, 27);
      leftLeg1.addBox(-5F, 2F, -2F, 2, 4, 4);
      leftLeg1.setRotationPoint(-1F, 16F, 0F);
      leftLeg1.setTextureSize(64, 64);
      leftLeg1.mirror = true;
      setRotation(leftLeg1, 0F, 0F, 0F);
      leftLeg2 = new ModelRenderer(this, 40, 35);
      leftLeg2.addBox(-6F, 6F, -3F, 4, 2, 6);
      leftLeg2.setRotationPoint(-1F, 16F, 0F);
      leftLeg2.setTextureSize(64, 64);
      leftLeg2.mirror = true;
      setRotation(leftLeg2, 0F, 0F, 0F);
      rightLeg2 = new ModelRenderer(this, 40, 43);
      rightLeg2.addBox(2F, 6F, -3F, 4, 2, 6);
      rightLeg2.setRotationPoint(1F, 16F, 0F);
      rightLeg2.setTextureSize(64, 64);
      rightLeg2.mirror = true;
      setRotation(rightLeg2, 0F, 0F, 0F);
      rightLeg1 = new ModelRenderer(this, 52, 27);
      rightLeg1.addBox(3F, 2F, -2F, 2, 4, 4);
      rightLeg1.setRotationPoint(1F, 16F, 0F);
      rightLeg1.setTextureSize(64, 64);
      rightLeg1.mirror = true;
      setRotation(rightLeg1, 0F, 0F, 0F);
      b = new ModelRenderer(this, 56, 0);
      b.addBox(-1F, -12F, -1F, 2, 16, 2);
      b.setRotationPoint(0F, 17F, 0F);
      b.setTextureSize(64, 64);
      b.mirror = true;
      setRotation(b, 0F, 0F, 0F);
      b1 = new ModelRenderer(this, 0, 47);
      b1.addBox(-3F, -10F, -3F, 6, 1, 6);
      b1.setRotationPoint(0F, 17F, 0F);
      b1.setTextureSize(64, 64);
      b1.mirror = true;
      setRotation(b1, 0F, 0F, 0F);
      b2 = new ModelRenderer(this, 0, 38);
      b2.addBox(-4F, -8F, -4F, 8, 1, 8);
      b2.setRotationPoint(0F, 17F, 0F);
      b2.setTextureSize(64, 64);
      b2.mirror = true;
      setRotation(b2, 0F, 0F, 0F);
      b3 = new ModelRenderer(this, 0, 27);
      b3.addBox(-5F, -6F, -5F, 10, 1, 10);
      b3.setRotationPoint(0F, 17F, 0F);
      b3.setTextureSize(64, 64);
      b3.mirror = true;
      setRotation(b3, 0F, 0F, 0F);
      b4 = new ModelRenderer(this, 0, 15);
      b4.addBox(-6F, -4F, -6F, 12, 1, 11);
      b4.setRotationPoint(0F, 17F, 0F);
      b4.setTextureSize(64, 64);
      b4.mirror = true;
      setRotation(b4, 0F, 0F, 0F);
      b5 = new ModelRenderer(this, 0, 0);
      b5.addBox(-7F, -2F, -7F, 14, 1, 14);
      b5.setRotationPoint(0F, 17F, 0F);
      b5.setTextureSize(64, 64);
      b5.mirror = true;
      setRotation(b5, 0F, 0F, 0F);
      b6 = new ModelRenderer(this, 0, 0);
      b6.addBox(-6F, 0F, -6F, 12, 1, 12);
      b6.setRotationPoint(0F, 17F, 0F);
      b6.setTextureSize(64, 64);
      b6.mirror = true;
      setRotation(b6, 0F, 0F, 0F);
      b7 = new ModelRenderer(this, 0, 47);
      b7.addBox(-3F, 2F, -3F, 6, 1, 6);
      b7.setRotationPoint(0F, 17F, 0F);
      b7.setTextureSize(64, 64);
      b7.mirror = true;
      setRotation(b7, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    leftLeg1.render(f5);
    leftLeg2.render(f5);
    rightLeg2.render(f5);
    rightLeg1.render(f5);
    b.render(f5);
    b1.render(f5);
    b2.render(f5);
    b3.render(f5);
    b4.render(f5);
    b5.render(f5);
    b6.render(f5);
    b7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
