// Date: 30.12.2017 19:49:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks

package net.zeldadungeons.client.render.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelProoper extends ModelBase {
    ModelRenderer head;
    ModelRenderer headc2;
    ModelRenderer headc1;
    ModelRenderer body;
    ModelRenderer rightLeg;
    ModelRenderer leftLeg;

    public ModelProoper() {
	textureWidth = 64;
	textureHeight = 64;

	head = new ModelRenderer(this, 0, 0);
	head.addBox(-6F, -11F, -2F, 12, 11, 5);
	head.setRotationPoint(0F, -3F, -1F);
	head.setTextureSize(64, 64);
	head.mirror = true;
	setRotation(head, 0F, 0F, 0F);
	headc2 = new ModelRenderer(this, 6, 30);
	headc2.addBox(2F, -4F, -3F, 2, 10, 1);
	headc2.setRotationPoint(0F, -3F, -1F);
	headc2.setTextureSize(64, 64);
	headc2.mirror = true;
	setRotation(headc2, 0F, 0F, 0F);
	headc1 = new ModelRenderer(this, 0, 30);
	headc1.addBox(-4F, -4F, -3F, 2, 10, 1);
	headc1.setRotationPoint(0F, -3F, -1F);
	headc1.setTextureSize(64, 64);
	headc1.mirror = true;
	setRotation(headc1, 0F, 0F, 0F);
	body = new ModelRenderer(this, 0, 16);
	body.addBox(-5F, 0F, -1F, 10, 11, 3);
	body.setRotationPoint(0F, -3F, 0F);
	body.setTextureSize(64, 64);
	body.mirror = true;
	setRotation(body, 0F, 0F, 0F);
	rightLeg = new ModelRenderer(this, 36, 23);
	rightLeg.addBox(0F, 0F, -3F, 7, 16, 7);
	rightLeg.setRotationPoint(1F, 8F, 0F);
	rightLeg.setTextureSize(64, 64);
	rightLeg.mirror = true;
	setRotation(rightLeg, 0F, 0F, 0F);
	leftLeg = new ModelRenderer(this, 36, 0);
	leftLeg.addBox(-7F, 0F, -3F, 7, 16, 7);
	leftLeg.setRotationPoint(-1F, 8F, 0F);
	leftLeg.setTextureSize(64, 64);
	leftLeg.mirror = true;
	setRotation(leftLeg, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
	GlStateManager.pushMatrix();
	setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	head.render(f5);
	headc2.render(f5);
	headc1.render(f5);
	body.render(f5);
	rightLeg.render(f5);
	leftLeg.render(f5);
	GlStateManager.popMatrix();

    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
	model.rotateAngleX = x;
	model.rotateAngleY = y;
	model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
	this.rightLeg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
	this.leftLeg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + (float) Math.PI) * 1.4F * limbSwingAmount;
    }

}
